var sourcesIndex = JSON.parse('{\
"bitflags":["",[],["lib.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"cosmic_protocols":["",[],["lib.rs","protocol_macro.rs"]],\
"dlib":["",[],["lib.rs"]],\
"downcast_rs":["",[],["lib.rs"]],\
"io_lifetimes":["",[],["example_ffi.rs","lib.rs","portability.rs","raw.rs","traits.rs","views.rs"]],\
"libc":["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"libloading":["",[["os",[["unix",[],["consts.rs","mod.rs"]]],["mod.rs"]]],["changelog.rs","error.rs","lib.rs","safe.rs","util.rs"]],\
"log":["",[],["__private_api.rs","lib.rs","macros.rs"]],\
"memchr":["",[["arch",[["all",[["packedpair",[],["default_rank.rs","mod.rs"]]],["memchr.rs","mod.rs","rabinkarp.rs","shiftor.rs","twoway.rs"]],["generic",[],["memchr.rs","mod.rs","packedpair.rs"]],["x86_64",[["avx2",[],["memchr.rs","mod.rs","packedpair.rs"]],["sse2",[],["memchr.rs","mod.rs","packedpair.rs"]]],["memchr.rs","mod.rs"]]],["mod.rs"]],["memmem",[],["mod.rs","searcher.rs"]]],["cow.rs","ext.rs","lib.rs","macros.rs","memchr.rs","vector.rs"]],\
"memoffset":["",[],["lib.rs","offset_of.rs","raw_field.rs","span_of.rs"]],\
"nix":["",[["sys",[["socket",[],["addr.rs","mod.rs","sockopt.rs"]]],["epoll.rs","eventfd.rs","memfd.rs","mod.rs","select.rs","signal.rs","stat.rs","statfs.rs","statvfs.rs","sysinfo.rs","time.rs","uio.rs"]]],["errno.rs","fcntl.rs","lib.rs","macros.rs","poll.rs","unistd.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"quick_xml":["",[["events",[],["attributes.rs","mod.rs"]],["reader",[],["buffered_reader.rs","mod.rs","ns_reader.rs","parser.rs","slice_reader.rs"]]],["encoding.rs","errors.rs","escapei.rs","lib.rs","name.rs","utils.rs","writer.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"scoped_tls":["",[],["lib.rs"]],\
"smallvec":["",[],["lib.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"wayland_backend":["",[["rs",[["client_impl",[],["mod.rs"]],["server_impl",[],["client.rs","common_poll.rs","handle.rs","mod.rs","registry.rs"]]],["debug.rs","map.rs","mod.rs","socket.rs","wire.rs"]],["types",[],["client.rs","mod.rs","server.rs"]]],["client_api.rs","core_interfaces.rs","lib.rs","protocol.rs","server_api.rs"]],\
"wayland_client":["",[],["conn.rs","event_queue.rs","globals.rs","lib.rs"]],\
"wayland_protocols":["",[],["ext.rs","lib.rs","protocol_macro.rs","wp.rs","xdg.rs","xwayland.rs"]],\
"wayland_scanner":["",[],["c_interfaces.rs","client_gen.rs","common.rs","interfaces.rs","lib.rs","parse.rs","protocol.rs","server_gen.rs","token.rs","util.rs"]],\
"wayland_server":["",[],["client.rs","dispatch.rs","display.rs","global.rs","lib.rs","socket.rs"]],\
"wayland_sys":["",[],["client.rs","common.rs","lib.rs","server.rs"]]\
}');
createSourceSidebar();
