var srcIndex = new Map(JSON.parse('[\
["bitflags",["",[],["external.rs","internal.rs","iter.rs","lib.rs","parser.rs","public.rs","traits.rs"]]],\
["cfg_if",["",[],["lib.rs"]]],\
["cosmic_protocols",["",[],["lib.rs","protocol_macro.rs"]]],\
["dlib",["",[],["lib.rs"]]],\
["downcast_rs",["",[],["lib.rs"]]],\
["io_lifetimes",["",[],["lib.rs","portability.rs","raw.rs","traits.rs","views.rs"]]],\
["libloading",["",[["os",[["unix",[],["consts.rs","mod.rs"]]],["mod.rs"]]],["changelog.rs","error.rs","lib.rs","safe.rs","util.rs"]]],\
["linux_raw_sys",["",[["x86_64",[],["errno.rs","general.rs","if_ether.rs","ioctl.rs","net.rs","netlink.rs","prctl.rs","xdp.rs"]]],["elf.rs","lib.rs"]]],\
["log",["",[],["__private_api.rs","lib.rs","macros.rs"]]],\
["memchr",["",[["arch",[["all",[["packedpair",[],["default_rank.rs","mod.rs"]]],["memchr.rs","mod.rs","rabinkarp.rs","shiftor.rs","twoway.rs"]],["generic",[],["memchr.rs","mod.rs","packedpair.rs"]],["x86_64",[["avx2",[],["memchr.rs","mod.rs","packedpair.rs"]],["sse2",[],["memchr.rs","mod.rs","packedpair.rs"]]],["memchr.rs","mod.rs"]]],["mod.rs"]],["memmem",[],["mod.rs","searcher.rs"]]],["cow.rs","ext.rs","lib.rs","macros.rs","memchr.rs","vector.rs"]]],\
["proc_macro2",["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]]],\
["quick_xml",["",[["events",[],["attributes.rs","mod.rs"]],["reader",[],["buffered_reader.rs","mod.rs","ns_reader.rs","slice_reader.rs","state.rs"]]],["encoding.rs","errors.rs","escapei.rs","lib.rs","name.rs","utils.rs","writer.rs"]]],\
["quote",["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]]],\
["rustix",["",[["backend",[["linux_raw",[["arch",[],["mod.rs","x86_64.rs"]],["event",[],["epoll.rs","mod.rs","poll_fd.rs","syscalls.rs","types.rs"]],["fs",[],["dir.rs","inotify.rs","makedev.rs","mod.rs","syscalls.rs","types.rs"]],["io",[],["errno.rs","mod.rs","syscalls.rs","types.rs"]],["mount",[],["mod.rs","syscalls.rs","types.rs"]],["net",[],["addr.rs","mod.rs","msghdr.rs","netdevice.rs","read_sockaddr.rs","send_recv.rs","sockopt.rs","syscalls.rs","write_sockaddr.rs"]],["param",[],["libc_auxv.rs","mod.rs"]],["pid",[],["mod.rs","syscalls.rs"]],["prctl",[],["mod.rs","syscalls.rs"]],["process",[],["cpu_set.rs","mod.rs","syscalls.rs","types.rs","wait.rs"]],["ugid",[],["mod.rs","syscalls.rs"]]],["c.rs","conv.rs","mod.rs","reg.rs","vdso.rs","vdso_wrappers.rs"]]]],["event",[],["eventfd.rs","mod.rs","pause.rs","poll.rs"]],["fs",[],["abs.rs","at.rs","constants.rs","copy_file_range.rs","cwd.rs","dir.rs","fadvise.rs","fcntl.rs","fd.rs","id.rs","ioctl.rs","makedev.rs","memfd_create.rs","mod.rs","mount.rs","openat2.rs","raw_dir.rs","seek_from.rs","sendfile.rs","statx.rs","sync.rs","xattr.rs"]],["io",[],["close.rs","dup.rs","errno.rs","fcntl.rs","ioctl.rs","is_read_write.rs","mod.rs","read_write.rs"]],["ioctl",[],["linux.rs","mod.rs","patterns.rs"]],["maybe_polyfill",[["std",[],["mod.rs"]]]],["mount",[],["mod.rs","mount_unmount.rs","types.rs"]],["net",[["send_recv",[],["mod.rs","msg.rs"]]],["mod.rs","netdevice.rs","socket.rs","socket_addr_any.rs","socketpair.rs","sockopt.rs","types.rs"]],["path",[],["arg.rs","mod.rs"]],["process",[],["chdir.rs","chroot.rs","exit.rs","id.rs","ioctl.rs","kill.rs","membarrier.rs","mod.rs","pidfd.rs","pidfd_getfd.rs","prctl.rs","priority.rs","rlimit.rs","sched.rs","sched_yield.rs","umask.rs","wait.rs"]]],["bitcast.rs","buffer.rs","cstr.rs","ffi.rs","lib.rs","pid.rs","prctl.rs","signal.rs","timespec.rs","ugid.rs","utils.rs","weak.rs"]]],\
["scoped_tls",["",[],["lib.rs"]]],\
["smallvec",["",[],["lib.rs"]]],\
["unicode_ident",["",[],["lib.rs","tables.rs"]]],\
["wayland_backend",["",[["rs",[["client_impl",[],["mod.rs"]],["server_impl",[],["client.rs","common_poll.rs","handle.rs","mod.rs","registry.rs"]]],["map.rs","mod.rs","socket.rs","wire.rs"]],["types",[],["client.rs","mod.rs","server.rs"]]],["client_api.rs","core_interfaces.rs","debug.rs","lib.rs","protocol.rs","server_api.rs"]]],\
["wayland_client",["",[],["conn.rs","event_queue.rs","globals.rs","lib.rs"]]],\
["wayland_protocols",["",[],["ext.rs","lib.rs","protocol_macro.rs","wp.rs","xdg.rs","xwayland.rs"]]],\
["wayland_scanner",["",[],["c_interfaces.rs","client_gen.rs","common.rs","interfaces.rs","lib.rs","parse.rs","protocol.rs","server_gen.rs","token.rs","util.rs"]]],\
["wayland_server",["",[],["client.rs","dispatch.rs","display.rs","global.rs","lib.rs","socket.rs"]]],\
["wayland_sys",["",[],["client.rs","common.rs","lib.rs","server.rs"]]]\
]'));
createSrcSidebar();
